FROM openjdk:17-jdk-slim

MAINTAINER spring-cloud-study-user-service.com

COPY target/spring-cloud-study-user-service-0.0.1-SNAPSHOT.jar spring-cloud-study-user-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "spring-cloud-study-user-service-0.0.1-SNAPSHOT.jar"]